# Generated by Django 3.0.6 on 2020-05-04 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=2)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.TextField(default='{"1a": "", "1b": "", "1c": "", "1d": "", "1e": "", "1f": "", "1g": "", "1h": "", "1i": "", "1j": "", "2a": "", "2b": "", "2c": "", "2d": "", "2e": "", "2f": "", "2g": "", "2h": "", "2i": "", "2j": "", "3a": "", "3b": "", "3c": "", "3d": "", "3e": "", "3f": "", "3g": "", "3h": "", "3i": "", "3j": "", "4a": "", "4b": "", "4c": "", "4d": "", "4e": "", "4f": "", "4g": "", "4h": "", "4i": "", "4j": "", "5a": "", "5b": "", "5c": "", "5d": "", "5e": "", "5f": "", "5g": "", "5h": "", "5i": "", "5j": "", "6a": "", "6b": "", "6c": "", "6d": "", "6e": "", "6f": "", "6g": "", "6h": "", "6i": "", "6j": "", "7a": "", "7b": "", "7c": "", "7d": "", "7e": "", "7f": "", "7g": "", "7h": "", "7i": "", "7j": "", "8a": "", "8b": "", "8c": "", "8d": "", "8e": "", "8f": "", "8g": "", "8h": "", "8i": "", "8j": "", "9a": "", "9b": "", "9c": "", "9d": "", "9e": "", "9f": "", "9g": "", "9h": "", "9i": "", "9j": "", "10a": "", "10b": "", "10c": "", "10d": "", "10e": "", "10f": "", "10g": "", "10h": "", "10i": "", "10j": ""}')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy_field', to='battle.Field')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Player')),
                ('player_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_field', to='battle.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=2)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Player')),
            ],
        ),
        migrations.CreateModel(
            name='ShipTwoDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='ShipThreeDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='ShipOneDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='ShipFourDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Deck')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='side1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side1', to='battle.Side'),
        ),
        migrations.AddField(
            model_name='game',
            name='side2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side2', to='battle.Side'),
        ),
        migrations.AddField(
            model_name='field',
            name='ship1d_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship4d_1', to='battle.ShipFourDeck'),
        ),
        migrations.AddField(
            model_name='field',
            name='ship1d_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship1d_2', to='battle.ShipOneDeck'),
        ),
        migrations.AddField(
            model_name='field',
            name='ship1d_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship1d_3', to='battle.ShipOneDeck'),
        ),
        migrations.AddField(
            model_name='field',
            name='ship1d_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship1d_4', to='battle.ShipOneDeck'),
        ),
        migrations.AddField(
            model_name='field',
            name='ship2d_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship2d_1', to='battle.ShipTwoDeck'),
        ),
        migrations.AddField(
            model_name='field',
            name='ship2d_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship2d_2', to='battle.ShipTwoDeck'),
        ),
        migrations.AddField(
            model_name='field',
            name='ship2d_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship2d_3', to='battle.ShipTwoDeck'),
        ),
        migrations.AddField(
            model_name='field',
            name='ship3d_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship3d_1', to='battle.ShipThreeDeck'),
        ),
        migrations.AddField(
            model_name='field',
            name='ship3d_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship3d_2', to='battle.ShipThreeDeck'),
        ),
    ]
