# Generated by Django 3.0.6 on 2020-05-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='ship1d_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship4d_1', to='battle.ShipFourDeck'),
        ),
        migrations.AlterField(
            model_name='field',
            name='ship1d_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship1d_2', to='battle.ShipOneDeck'),
        ),
        migrations.AlterField(
            model_name='field',
            name='ship1d_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship1d_3', to='battle.ShipOneDeck'),
        ),
        migrations.AlterField(
            model_name='field',
            name='ship1d_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship1d_4', to='battle.ShipOneDeck'),
        ),
        migrations.AlterField(
            model_name='field',
            name='ship2d_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship2d_1', to='battle.ShipTwoDeck'),
        ),
        migrations.AlterField(
            model_name='field',
            name='ship2d_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship2d_2', to='battle.ShipTwoDeck'),
        ),
        migrations.AlterField(
            model_name='field',
            name='ship2d_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship2d_3', to='battle.ShipTwoDeck'),
        ),
        migrations.AlterField(
            model_name='field',
            name='ship3d_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship3d_1', to='battle.ShipThreeDeck'),
        ),
        migrations.AlterField(
            model_name='field',
            name='ship3d_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship3d_2', to='battle.ShipThreeDeck'),
        ),
    ]
